# Generated by Django 3.1.7 on 2021-04-06 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_dealership'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomVehicleAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=100)),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.dealership')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=25, unique=True)),
                ('int_color', models.CharField(max_length=50)),
                ('ext_color', models.CharField(max_length=50)),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.dealership')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.customvehicleattribute')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.vehicle')),
            ],
        ),
    ]
