# Generated by Django 3.1.7 on 2021-04-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customvehicleattribute',
            name='visible_inventory',
            field=models.BooleanField(default=False),
        ),
    ]
