# Generated by Django 3.1.7 on 2021-04-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_customvehicleattribute_visible_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customvehicleattribute',
            name='order_position',
            field=models.IntegerField(default=0),
        ),
    ]
