# Generated by Django 3.1.7 on 2021-04-07 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_customvehicleattribute_order_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='customvehicleattribute',
            name='attribute_type',
            field=models.CharField(default=str, max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CustomVehicleAttributeOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.customvehicleattribute')),
            ],
        ),
    ]
