# Generated by Django 3.1.7 on 2021-04-09 20:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20210406_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='ext_color',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='int_color',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='IntegerVehicleAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.customvehicleattribute')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='DateTimeVehicleAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DateTimeField(auto_now_add=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.customvehicleattribute')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyVehicleAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.customvehicleattribute')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.vehicle')),
            ],
        ),
    ]
