# Generated by Django 3.2 on 2021-04-12 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20210409_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencyvehicleattribute',
            old_name='value',
            new_name='decimal_value',
        ),
        migrations.RenameField(
            model_name='datetimevehicleattribute',
            old_name='value',
            new_name='date_time_value',
        ),
        migrations.RenameField(
            model_name='integervehicleattribute',
            old_name='value',
            new_name='integer_value',
        ),
        migrations.RemoveField(
            model_name='currencyvehicleattribute',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='datetimevehicleattribute',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='integervehicleattribute',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='vehicleattribute',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='vehicleattribute',
            name='value',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='currencyvehicleattribute',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.vehicleattribute'),
        ),
        migrations.AlterField(
            model_name='datetimevehicleattribute',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.vehicleattribute'),
        ),
        migrations.AlterField(
            model_name='integervehicleattribute',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.vehicleattribute'),
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.customvehicleattribute')),
                ('vehicle_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.vehicleattribute', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StringVehicleAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_value', models.CharField(max_length=200)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.vehicleattribute')),
            ],
        ),
    ]
