# Generated by Django 3.2 on 2021-04-12 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20210412_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletype',
            name='vehicle_attribute',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.vehicleattribute'),
        ),
    ]
