# Generated by Django 3.2 on 2021-04-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_vehicle_arrived_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetimevehicleattribute',
            name='date_time_value',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='arrived_on',
            field=models.DateField(),
        ),
    ]
