# Generated by Django 3.2 on 2021-04-16 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20210412_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencyvehicleattribute',
            old_name='vehicle',
            new_name='vehicle_attribute',
        ),
        migrations.RenameField(
            model_name='datetimevehicleattribute',
            old_name='vehicle',
            new_name='vehicle_attribute',
        ),
        migrations.RenameField(
            model_name='integervehicleattribute',
            old_name='vehicle',
            new_name='vehicle_attribute',
        ),
        migrations.RenameField(
            model_name='stringvehicleattribute',
            old_name='vehicle',
            new_name='vehicle_attribute',
        ),
    ]
