# Generated by Django 3.2 on 2021-04-16 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_dealershipuser'),
        ('inventory', '0010_auto_20210416_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=7)),
                ('description', models.TextField()),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.dealership')),
            ],
        ),
    ]
