# Generated by Django 3.2 on 2021-04-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_location_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='Home Location', max_length=50),
            preserve_default=False,
        ),
    ]
