# Generated by Django 3.2 on 2021-04-16 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_location_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.vehicle')),
            ],
        ),
    ]
