# Generated by Django 3.2 on 2021-04-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_vehiclelocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
