# Generated by Django 3.2 on 2021-04-18 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20210416_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletype',
            name='vehicle_attribute',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_attribute', to='inventory.vehicleattribute'),
        ),
    ]
